language: java
jdk:
  - openjdk11
script:
  - mvn clean install
cache:
  directories:
    - $HOME/.m2
version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud